### ISSUE TITLE
SocketException on client closing the websocket session

### ISSUE THREAD

**Issue by dzlab** [NanoHttpd/nanohttpd#147]
I'm running the `EchoSocketSample` web socket server, with a client using `javax.websocket-api` and [tyrus](https://tyrus.java.net/) as the implementation. Here is how the client is establishing a connection to the server:
```java
public static void main(String[] args)
  {
    WebSocketContainer container = null;
    Session session = null;
    try
    {
      container = ContainerProvider.getWebSocketContainer();
      session = container.connectToServer(WSClient.class, URI.create("ws://localhost:8081/"));
      session.getBasicRemote().sendText("hello web socket server");
      Thread.sleep(1000);
      LOG.info("Done.");
    }
    catch (Exception e)
    {
      e.printStackTrace();
    }
    {
      if (session != null)
      {
        try
        {
          session.close();
        }
        catch (Exception e)
        {
          e.printStackTrace();
        }
      }
    }
  }
```
When the client close the session, then a SocketException is raised on the server as it attempts to write to the closed socket (It should not). Here is the full stack trace:
```java
java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:138)
	at fi.iki.elonen.WebSocketFrame.write(WebSocketFrame.java:246)
	at fi.iki.elonen.WebSocket.sendFrame(WebSocket.java:147)
	at fi.iki.elonen.samples.echo.DebugWebSocket.sendFrame(DebugWebSocket.java:65)
	at fi.iki.elonen.WebSocket.handleCloseFrame(WebSocket.java:114)
	at fi.iki.elonen.WebSocket.handleWebsocketFrame(WebSocket.java:83)
	at fi.iki.elonen.samples.echo.DebugWebSocket.handleWebsocketFrame(DebugWebSocket.java:57)
	at fi.iki.elonen.WebSocket.readWebsocket(WebSocket.java:66)
	at fi.iki.elonen.WebSocket$1.send(WebSocket.java:39)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:926)
	at fi.iki.elonen.NanoHTTPD$1$1.run(NanoHTTPD.java:175)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by ritchieGitHub** [comment]
socket timeout can now be set when starting, a negative timeout will set no timeout
