### ISSUE TITLE
NanoHttpd throws an exception if temp directory doesn't exist

### ISSUE THREAD

**Issue by fedotxxl** [NanoHttpd/nanohttpd#243]
````
Exception in thread "NanoHttpd Request Processor (#30)" java.lang.Error: java.io.IOException: No such file or directory
        at fi.iki.elonen.NanoHTTPD$HTTPSession.getTmpBucket(NanoHTTPD.java:1271)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.parseBody(NanoHTTPD.java:985)
        at com.project.HttpServer.getPostBody(HttpServer.java:73)
        at com.project.HttpServer.serve(HttpServer.java:45)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:953)
        at fi.iki.elonen.NanoHTTPD$1$1.run(NanoHTTPD.java:208)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at fi.iki.elonen.NanoHTTPD$DefaultTempFile.<init>(NanoHTTPD.java:545)
        at fi.iki.elonen.NanoHTTPD$DefaultTempFileManager.createTempFile(NanoHTTPD.java:517)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.getTmpBucket(NanoHTTPD.java:1268)
        ... 6 more
````

**Comment by vnnv** [comment]
This can be fixed using .mkdirs(); Unfortunately I have no write rights to make a commit.

**Comment by ritchieGitHub** [comment]
you can create a pull request, but how can it be that in your case the tmp directory does not exist?

**Comment by vnnv** [comment]
It is possible that java.io.tmp is passed as jvm argument and is different than /tmp. Quite possible if you'd like to have 20GB tmp directory :)

**Comment by vnnv** [comment]
I'll submit pull request after 5 min

**Comment by ritchieGitHub** [comment]
that's ok but java isself assumes the java.io.tmp directory is an exisiting directory. So would it not be better to provide a own property that superseeds the java.io.tmp ?

**Comment by vnnv** [comment]
on unix machines java assumes that java.io.tmpdir is /tmp and it should exist. usually it is mounted as tmpfs with size half of the installed ram. 
but in case you like to have more temp space you must set java.io.tmpdir on the command line with -Djava.io.tmpdir=new_dir
In another project I had a problem uploading 10 GB file just because my /tmp is 8GB. If you pass a value to java.io.tmpdir it is possible that the directory is not created. 
Anyway, I think that own property is not needed. If new property is introduced than you have to specify it every time you run the project.

**Comment by ritchieGitHub** [comment]
ok, i will include your pull request (please include a unit test) as soon as you are ready

**Comment by vnnv** [comment]
I added a unit test.

**Comment by ritchieGitHub** [comment]
added with some adaptions
