### ISSUE TITLE
Using HTTP on HTTPS endpoint returns a 200 Status

### ISSUE THREAD

**Issue by jpeyper** [NanoHttpd/nanohttpd#264]
I have a simple server setup to use a JKS keystore in Java 8:
```java
import fi.iki.elonen.NanoHTTPD;

import javax.net.ssl.KeyManagerFactory;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.UnrecoverableKeyException;
import java.security.cert.CertificateException;

public class MySimpleServer extends NanoHTTPD {
    public static void main(String[] args) {
        try {
            int port = Integer.parseInt(args[0]);
            String keystoreFile = args[1];
            String keystorePassword = args[2];

            KeyStore keyStore = KeyStore.getInstance("JKS");
            try (InputStream in = new FileInputStream(keystoreFile)) {
                keyStore.load(in, null);
            }
            KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            keyManagerFactory.init(keyStore, keystorePassword.toCharArray());

            MySimpleServer server = new MySimpleServer(port);
            server.makeSecure(NanoHTTPD.makeSSLSocketFactory(keyStore, keyManagerFactory), null);
            server.start(NanoHTTPD.SOCKET_READ_TIMEOUT, false);

        } catch (IOException e) {
            System.err.println("Couldn't start server:\n" + e);
        } catch (NumberFormatException e) {
            System.err.println("Invalid port specified: " + args[0]);
        } catch (CertificateException | KeyStoreException | UnrecoverableKeyException | NoSuchAlgorithmException e) {
            System.err.println("HTTPS certificate error:\n " + e);
        }
    }

    public MySimpleServer(int port) {
        super(port);
    }

    @Override
    public Response serve(IHTTPSession session) {
        if (!session.getUri().equalsIgnoreCase("/info"))
            return newFixedLengthResponse(Response.Status.NOT_FOUND, "text/plain", "Resource not found.");

        if (!session.getMethod().equals(Method.GET))
            return newFixedLengthResponse(Response.Status.METHOD_NOT_ALLOWED, "text/plain", "Method not allowed.");

        String response = "{\"working\":{}}";
        return newFixedLengthResponse(NanoHTTPD.Response.Status.OK, "application/json", response);
    }
}
```

`MySimpleServer` is a class that extends `NanoHTTPD` and has a single endpoint `/info` that returns some json.

This works fine and if I go to `https://localhost:8443/info`, I get the expected result.

However, if I go to anything on the http protocol (ie, `http://localhost:8443/<anything>`), Postman tells me I get a 200 OK response, which isn't great.

So that is the gist of my issue, I have spent some time trying to figure out if I can fix it or why it is doing what it is doing, so please disregard everything below this point if its wrong or confusing.

Debugging through the code, I get to line 782 in NanoHTTPD.java which catches this exception
```
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
````
and then does this
```java
throw new SocketException("NanoHttpd Shutdown");
```
Which then goes down to line 859 and throws it again.

Outside the execute method, in the run method, there is this interesting bit of code
```java
catch (Exception e) {
    // When the socket is closed by the client,
    // we throw our own SocketException
    // to break the "keep alive" loop above. If
    // the exception was anything other
    // than the expected SocketException OR a
    // SocketTimeoutException, print the
    // stacktrace
    if (!(e instanceof SocketException && "NanoHttpd Shutdown".equals(e.getMessage())) && !(e instanceof SocketTimeoutException)) {
    NanoHTTPD.LOG.log(Level.FINE, "Communication with the client broken", e);
}
```
This is false (as its a `SocketException` with the message `NanoHtttpd Shutdown`) and therefore doesn't log anything.

That's as far as I've gotten.

**Comment by ritchieGitHub** [comment]
Should be better now, can you try it with the current snapshot?

**Comment by jpeyper** [comment]
You'll have to excuse my inexperience, I'm using maven to get 2.2.0 in intellij,

I've tried changing the version to `SNAPSHOT`, `2.3-SNAPSHOT` and `2.3.0` (based ont he 2.3.0 milestone).

If I put in `LATEST` I get version 2.2.1 (I was using  2.2.0 before), is this the correct version I should be trying? Because it still has the problem.

**Comment by jpeyper** [comment]
Also, I believe this to be a bug not an enhancement, returning a 200 OK response when the server raises an exception is broken.

**Comment by ritchieGitHub** [comment]
to use a snapshot see https://github.com/NanoHttpd/nanohttpd#living-on-the-edge 
(you need the snapshot repository entry in your pom)

**Comment by jpeyper** [comment]
Using the snapshot repository and version  `LATEST` (which resolves to `2.2.1-SNAPSHOT`), I still have the issue, doing a `GET` to `http://localhost:8443` using postman returns a 200 OK status code.

The debug output is
```
Dec 23, 2015 10:17:12 AM fi.iki.elonen.NanoHTTPD$Response send
SEVERE: Could not send response to the client
javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1541)
	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1553)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
	at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1543)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1516)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1506)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1474)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:878)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:191)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:928)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:787)
	... 2 more
```

**Comment by ritchieGitHub** [comment]
the log is as expected but the client should not get an  200/OK, could you please adapt the unit test fi.iki.elonen.HttpSSLServerTest.testHttpOnSSLConnection() so that it fails with an 200/OK

thanks!

**Comment by jpeyper** [comment]
I have checked out the code and made the following change, however I wanted to check if I am right...
```
    @Test
    public void testHttpOnSSLConnection() throws IOException {
        DefaultHttpClient httpclient = new DefaultHttpClient();
        HttpTrace httphead = new HttpTrace("http://localhost:9043/index.html");
        HttpResponse response = httpclient.execute(httphead);

        Assert.assertEquals(response.getStatusLine().getStatusCode(), NanoHTTPD.Response.Status.INTERNAL_ERROR);
    }
```
Currently, the test is expecting a `ClientProtocolException`, which has an inner exception `ProtocolException` with the message `The server failed to respond with a valid HTTP response`

Is the exception it was expecting before correct? In which case I'm not sure why I'm getting a 200/OK in postman in my application.

**Comment by ritchieGitHub** [comment]
the exception is correct, because the data comming back ober the ssl connection can not be interpreted as a http response (for http it's just rubbish). maybe the postman try's to be "inteligent" and detects it as a SSL response and ......
So I think the problem is in the postman.

**Comment by ritchieGitHub** [comment]
moved this to after the refactoring (if it can be fixed earlier I will move this back), it is just no show stopper for 2.3.0
