### ISSUE TITLE
Response 304. But chrome can't Parse.

### ISSUE THREAD

**Issue by hanxi** [NanoHttpd/nanohttpd#268]
I use webserver in android 4.3 . In index.html include some css and js file. When refresh browser, some request css and js file are response 304 and the response text are not normal, They are begin some binary bytes with http header.

**Comment by ritchieGitHub** [comment]
we need more details to be able to help you. What does the webserver log say? did you trace the communication using a sniffer? (wireshark)

**Comment by hanxi** [comment]
I use SimpleWebServer with this in android.
```java
mHTTPSrv = new SimpleWebServer(null, port, wwwRoot, true, "*");
```
Then in PC Chrome visit this webserver, and refresh twice. the console error is this:
![image](https://cloud.githubusercontent.com/assets/1185757/11924292/f7a763fc-a7e9-11e5-919c-f3a16634242e.png)

And response is this:
![image](https://cloud.githubusercontent.com/assets/1185757/11924317/402aaaee-a7ea-11e5-8952-2e0fd4e5bffd.png)

trace is this:
```
12-21 14:02:06.367 27723-29409/info.hanxi.phoneservice E/fi.iki.elonen.NanoHTTPD: Could not send response to the client
                                                                                  java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                                                                                      at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:510)
                                                                                      at libcore.io.IoBridge.sendto(IoBridge.java:479)
                                                                                      at java.net.PlainSocketImpl.write(PlainSocketImpl.java:508)
                                                                                      at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
                                                                                      at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:270)
                                                                                      at java.io.OutputStream.write(OutputStream.java:82)
                                                                                      at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1261)
                                                                                      at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1247)
                                                                                      at java.util.zip.GZIPOutputStream.writeLong(GZIPOutputStream.java:112)
                                                                                      at java.util.zip.GZIPOutputStream.finish(GZIPOutputStream.java:95)
                                                                                      at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1451)
                                                                                      at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1440)
                                                                                      at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1429)
                                                                                      at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:852)
                                                                                      at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
                                                                                      at java.lang.Thread.run(Thread.java:841)
                                                                                   Caused by: libcore.io.ErrnoException: sendto failed: EPIPE (Broken pipe)
                                                                                      at libcore.io.Posix.sendtoBytes(Native Method)
                                                                                      at libcore.io.Posix.sendto(Posix.java:155)
                                                                                      at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
                                                                                      at libcore.io.IoBridge.sendto(IoBridge.java:477)
                                                                                      at java.net.PlainSocketImpl.write(PlainSocketImpl.java:508) 
                                                                                      at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46) 
                                                                                      at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:270) 
                                                                                      at java.io.OutputStream.write(OutputStream.java:82) 
                                                                                      at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1261) 
                                                                                      at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1247) 
                                                                                      at java.util.zip.GZIPOutputStream.writeLong(GZIPOutputStream.java:112) 
                                                                                      at java.util.zip.GZIPOutputStream.finish(GZIPOutputStream.java:95) 
                                                                                      at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1451) 
                                                                                      at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1440) 
                                                                                      at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1429) 
                                                                                      at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:852) 
                                                                                      at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189) 
                                                                                      at java.lang.Thread.run(Thread.java:841) 
```

**Comment by giridharkannan** [comment]
This issue happens because **Transfer-Encoding: chunked** is set, which is because **Content-Encoding: gzip** is set for 304 response.
For time being your could override useGzipWhenAccepted method to solve this issue.

```java
    @Override
    protected boolean useGzipWhenAccepted(Response r) {
        return super.useGzipWhenAccepted(r) && r.getStatus() != Response.Status.NOT_MODIFIED;
    }
```

**Comment by hanxi** [comment]
@giridharkannan Thanks a lot! It solved my problem.
```java
// SimpleWebServer.java
...
public class SimpleWebServer extends NanoHTTPD {

    @Override
    protected boolean useGzipWhenAccepted(Response r) {
        return super.useGzipWhenAccepted(r) && r.getStatus() != Response.Status.NOT_MODIFIED;
    }
...
```
