### ISSUE TITLE
NullPointer in ServerRunnable

### ISSUE THREAD

**Issue by aaqibkhan** [NanoHttpd/nanohttpd#270]
I am on NanoHttpd v2.2.0.
It was working nicely for couple of weeks until recently I started getting this error suddenly.

```java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.FileDescriptor.setInt$(int)' on a null object reference
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:93)
	at java.net.ServerSocket.implAccept(ServerSocket.java:216)
	at java.net.ServerSocket.accept(ServerSocket.java:140)
	at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1570)
	at java.lang.Thread.run(Thread.java:818)```

**Comment by ritchieGitHub** [comment]
This is a timing issue, should be fixed in the SNAPSHOT, could you try that?

**Comment by ritchieGitHub** [comment]
assumed working, if not please reopen

**Comment by shaobin0604** [comment]
I'm using 2.3.0, still have this issue sometimes

```
07-10 11:30:16.744 23004-23659/com.xxx.client E/AndroidRuntime: FATAL EXCEPTION: NanoHttpd Main Listener
                                                                    Process: com.xxx.client, PID: 23004
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.FileDescriptor.setInt$(int)' on a null object reference
                                                                        at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:93)
                                                                        at java.net.ServerSocket.implAccept(ServerSocket.java:217)
                                                                        at java.net.ServerSocket.accept(ServerSocket.java:141)
                                                                        at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1695)
                                                                        at java.lang.Thread.run(Thread.java:818)
```

**Comment by MrStanaland** [comment]
@shaobin0604 

I just ran into this issue and fixed it, so maybe this will help.  The problem (for me) was Splunk Mint, whose documentation states the following: "Currently, there are known compatibility issues with network monitoring and certain external libraries such as OkHttp, resulting in crashes. Splunk is currently working on this issue, but until it is resolved, disable network monitoring entirely if you experience this issue"

The full documentation is here:
http://docs.splunk.com/Documentation/MintAndroidSDK/5.1.x/DevGuide/Disablenetworkmonitoring

To fix the problem, I had to disable Splunk Mint network monitoring:
Mint.disableNetworkMonitoring();
Mint.initAndStartSession(MyActivity.this, "YOUR_API_KEY");

**Comment by dmsherazi** [comment]
I confirm that the above solution by @MrStanaland  works ... 

Thanks @MrStanaland for sharing this...

**Comment by bhumikash-tech** [comment]
@MrStanaland  can you please tell me where to add : 
Mint.disableNetworkMonitoring();
Mint.initAndStartSession(MyActivity.this, "YOUR_API_KEY");

I didn't get this. I will be really grateful if you help. 
Thanks
