### ISSUE TITLE
Cannot get response via HTTPS

### ISSUE THREAD

**Issue by gam2046** [NanoHttpd/nanohttpd#289]
```java
public class TestHTTPD extends NanoHTTPD {

    public TestHTTPD(int port) {
        super(port);
    }

    @Override
    public Response serve(IHTTPSession session) {
        String html = "<html>" +
                "<head>" +
                "<title>Test Html</title>" +
                "</head>" +
                "<body>" +
                "<h1>Now is " + new Date().toLocaleString() + "</h1>" +
                "</body>" +
                "</html>";
        return NanoHTTPD.newFixedLengthResponse(NanoHTTPD.Response.Status.OK, NanoHTTPD.MIME_HTML, html);
    }
}
```
```java
public class SslTest {

    @Test
    public void ssl() throws IOException {
        NanoHTTPD httpd = new TestHTTPD(8081);
        
        httpd.makeSecure(NanoHTTPD.makeSSLSocketFactory("/keystore.jks", "123456".toCharArray()), null);

        httpd.start(5000, false);

        while (true) System.in.read();
    }
}
```

I try to access `http://127.0.0.1:8081`, get the http-code 200 within an error, but there is no content.
```text
Could not send response to the client
javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1541)
	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1553)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
	at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1620)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1593)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1583)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1550)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:952)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:928)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:861)
	... 2 more
```
I try to access `https://127.0.0.1:8081`, can't get any response.The program did not throw any exceptions.

**Comment by ritchieGitHub** [comment]
@gam2046 it seems you found the solution yourself, but for the protocol and other users searching for solutions it would be great if you explain the solution in a few words here, thanks.

**Comment by gam2046** [comment]
Actually, I don't know why. I just did it in the way that [stackoverflow](http://stackoverflow.com/questions/31270613/https-server-on-android-device-using-nanohttpd) did it, and then it was right. However, the magic is that when I use the above code again, the results are correct.
Now I am not sure why this is the case, it is really amazing, by the way, I use the JDK8

**Comment by ritchieGitHub** [comment]
@gam2046 thanks for the link!
