### ISSUE TITLE
WARNING: could not delete file - Windows 7 64 bit -  multipart/form-data

### ISSUE THREAD

**Issue by CThuleHansen** [NanoHttpd/nanohttpd#296]
When I am uploading files to my nanohttpd server and debug through it, it creates two files in my user\appdata\local\temp folder. The files are the same, but with different names.
Once I return a response, one of the files get deleted, but the other file remains and the following exception is thrown: 
```
mar. 29, 2016 8:38:18 PM fi.iki.elonen.NanoHTTPD$DefaultTempFileManager clear
WARNING: could not delete file 
java.lang.Exception: could not delete temporary file
	at fi.iki.elonen.NanoHTTPD$DefaultTempFile.delete(NanoHTTPD.java:400)
	at fi.iki.elonen.NanoHTTPD$DefaultTempFileManager.clear(NanoHTTPD.java:443)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:875)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
	at java.lang.Thread.run(Thread.java:745)

```

I have not done anything to instantiate a particular filemanager, so I assume it to uses the default.

I am using version 2.3.0

**Comment by CThuleHansen** [comment]
Sorry, copy of #279
