### ISSUE TITLE
SocketException ECONNRESET - ChunkedOutputStream

### ISSUE THREAD

**Issue by CaiqueBrito** [NanoHttpd/nanohttpd#306]
Hello,

#Android 

I`m using SimpleWebServer class and im receiving a lot of SocketException, dont know if keepAlive property could be generating this problem, can i set the property keepAlive on my server instance?

Error By Logcat:
```
NanoHTTPD: Could not send response to the client
                                                                    java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
                                                                        at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:542)
                                                                        at libcore.io.IoBridge.sendto(IoBridge.java:511)
                                                                        at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
                                                                        at java.net.PlainSocketImpl.-wrap1(PlainSocketImpl.java)
                                                                        at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
                                                                        at java.io.OutputStream.write(OutputStream.java:82)
                                                                        at com.accenture.bsafrapoc.utils.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1233)
                                                                        at com.accenture.bsafrapoc.utils.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1219)
                                                                        at java.util.zip.GZIPOutputStream.writeShort(GZIPOutputStream.java:125)
                                                                        at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:82)
                                                                        at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:54)
                                                                        at com.accenture.bsafrapoc.utils.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1421)
                                                                        at com.accenture.bsafrapoc.utils.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1412)
                                                                        at com.accenture.bsafrapoc.utils.NanoHTTPD$Response.send(NanoHTTPD.java:1401)
                                                                        at com.accenture.bsafrapoc.utils.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:824)
                                                                        at com.accenture.bsafrapoc.utils.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:161)
                                                                        at java.lang.Thread.run(Thread.java:818)
```

Waiting for answer.

Thanks.

**Comment by CaiqueBrito** [comment]
I saw this error: `no mime types found in the classpath! please provide mimetypes.properties`

**Comment by fit-aditya** [comment]
Were you able to find a solution to this?
