### ISSUE TITLE
NanoWSD has a bug when a client initiates the close

### ISSUE THREAD

**Issue by feixiangsmile** [NanoHttpd/nanohttpd#328]
hi all, I use an client to connect to the server based on NanoWSD.  But, when the client initiates the close to server, the server will print a message with the closecode  InternalServerError on onClose function, but I think the correct closecode is normalclose(1000) in this situation. I debug the source code,I find the problem  code is:
private void readWebsocket() {
            try {
                while (this.state == State.OPEN) {
                    handleWebsocketFrame(WebSocketFrame.read(this.in));
                }
            } catch (CharacterCodingException e) {
                onException(e);
                doClose(CloseCode.InvalidFramePayloadData, e.toString(), false);
            } catch (IOException e) {
                onException(e);
                if (e instanceof WebSocketException) {
                    doClose(((WebSocketException) e).getCode(), ((WebSocketException) e).getReason(), false);
                }
            } finally {
                doClose(CloseCode.InternalServerError, "Handler terminated without closing the connection.", false);
            }
        }
the problem is at the finally branch. when server get a close request from client,the 'while' experssion is true ,so the 'while body' is executed. But when the 'while body' returns, the experssion is not true(because the state becomes 'closing'). However, at the state of connect is closing, the finnally branch is executed, which make the closecode to become 'CloseCode.InternalServerError', and the reason of close is "Handler terminated without closing the connection.". But the correct reason is normal close initiated by remote client. I am very sorry, I don't find a method to fix this. who can fix it? 3ks

**Comment by LordFokas** [comment]
Edited for code formatting and stuff.
Lately I've been deeper into NanoWSD than anyone else in the team.
Seems to me like the lack of a `doClose()` after the while, but it might actually be more than that...
I'll look into it when I have the time, if nobody else does.

**Comment by bachphuc** [comment]
Hi, I have same isues. I reslove by add param Timeout = 0 when start websocket (instance of NanoBSD)
Like this: websocket.start(0)
It's working well with me.

**Comment by samczsun** [comment]
Any update to this issue? I'm getting these statements in my log:

```[2016-12-07 21:11:23] [INFO] Received close frame in websocket 14, code=NormalClosure, reason=Normal connection closure
java.lang.Exception: Trace
        at com.samczsun.mpapi.websockets.GlobalWebsocket.debugFrameReceived(GlobalWebsocket.java:190)
        at fi.iki.elonen.NanoWSD$WebSocket.handleWebsocketFrame(NanoWSD.java:217)
        at fi.iki.elonen.NanoWSD$WebSocket.readWebsocket(NanoWSD.java:247)
        at fi.iki.elonen.NanoWSD$WebSocket.access$200(NanoWSD.java:65)
        at fi.iki.elonen.NanoWSD$WebSocket$1.send(NanoWSD.java:88)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:745)
```

And then in `onClose`

```[2016-12-07 21:11:23] [INFO] Websocket 14 closed with code=InternalServerError, reason=Handler terminated without closing the connection., remote=false```

It looks like `close` is called but not `doClose`, which means the state is still `CLOSING` when the finally block kicks in
