### ISSUE TITLE
Long URL causes broken pipe

### ISSUE THREAD

**Issue by jadams41** [NanoHttpd/nanohttpd#362]
I accidentally pasted a base64 encoded image (GET `10.1.10.115:9090/png;base64,R0lGODlhAAEAAff/`... to the port I am listening on and like would be expected I received: 
```
<html>
    <body>
        <h3>Error 404: the requested page doesn't exist.</h3>
    </body>
</html>
```
However, on the next request (now correct url `10.1.10.115:9090/api/ad`) I received the expected response but began constantly erroring on the server:
```
E/NanoHTTPD: Could not send response to the client
             java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                 at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:499)
                 at libcore.io.IoBridge.sendto(IoBridge.java:468)
                 at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507)
                 at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
                 at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
                 at android.services.http.NanoHTTPBase.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1619)
                 at android.services.http.NanoHTTPBase.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1592)
                 at android.services.http.NanoHTTPBase.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1582)
                 at android.services.http.NanoHTTPBase.NanoHTTPD$Response.send(NanoHTTPD.java:1549)
                 at android.services.http.NanoHTTPBase.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:936)
                 at android.services.http.NanoHTTPBase.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:191)
                 at java.lang.Thread.run(Thread.java:841)
              Caused by: libcore.io.ErrnoException: sendto failed: EPIPE (Broken pipe)
                 at libcore.io.Posix.sendtoBytes(Native Method)
                 at libcore.io.Posix.sendto(Posix.java:156)
                 at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
                 at libcore.io.IoBridge.sendto(IoBridge.java:466)
                 at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507) 
                 at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46) 
                 at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269) 
                 at android.services.http.NanoHTTPBase.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1619) 
                 at android.services.http.NanoHTTPBase.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1592) 
                 at android.services.http.NanoHTTPBase.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1582) 
                 at android.services.http.NanoHTTPBase.NanoHTTPD$Response.send(NanoHTTPD.java:1549) 
                 at android.services.http.NanoHTTPBase.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:936) 
                 at android.services.http.NanoHTTPBase.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:191) 
                 at java.lang.Thread.run(Thread.java:841) 
```
I am still able to access the api and receive responses, however, these errors print continuously until I kill the app.

Interestingly enough, the error seems identical to #232, however the cause seems different as the response is not very large.

I am able to reproduce this every time (and it doesn't need to be anything in particular, just a really long string, the shortest of which I have been able to produce this with is 8000 characters).

**Comment by WilliamDo** [comment]
I tried debugging this and it came down to the header size which includes the URL. If the URL is greater than ~8000 chars as mentioned above, the HTTP session enters an infinite loop because it relies on reading the `InputStream` throwing an exception to complete the request. The code below accidentally resets the stream every iteration because it can't find the end of the header in the fixed size buffer.

```java
while (read > 0) {
    this.rlen += read;
    this.splitbyte = findHeaderEnd(buf, this.rlen);
    if (this.splitbyte > 0) {
        break;
    }
    read = this.inputStream.read(buf, this.rlen, HTTPSession.BUFSIZE - this.rlen);
}

if (this.splitbyte < this.rlen) {
    this.inputStream.reset();
    this.inputStream.skip(this.splitbyte);
}
```
From the client point of view, the session however does complete for GET requests because we are at least able to parse the first ~8000 characters of the header which provides a workable although incomplete URL. The server ends up with a never-ending thread and will continue to process other requests. (I haven't tested POST).

Those who need a workaround this can increase the `HttpSession.BUFSIZE`.

Would like to help but I'm not sure what the solution should be here though - perhaps throwing an exception and return a 414?

**Comment by LordFokas** [comment]
The way to handle too large urls or http heads (not the header, the whole packet's head) is thoroughly specified in the RFCs that define the protocol.

For large heads there is HTTP 421 Entity Too Large, but I think there's a better error code for URLs, I don't remember.

The way to go about this would be to include detection for this situation and then respond with the appropriate error if applicable.

**Comment by stefan-reich** [comment]
Is this being fixed officially? It caused me some pain... I'll try and hack in a solution (limiting URI to 8KB).

**Comment by stefan-reich** [comment]
OK, here's my fix - ugly but works. After

    this.rlen += read;

add

    if (rlen >= buf.length) throw new RuntimeException("Header too big (" + rlen + " bytes)");

This really needs to be added - a production server without this fix can easily be brought down completely!

**Comment by byzhou** [comment]
Please fix this issue it is not a malformed request
