### ISSUE TITLE
 EPIPE (Broken pipe) on android platform

### ISSUE THREAD

**Issue by aemonfly** [NanoHttpd/nanohttpd#392]
we will get Broken pipe error from nanoHttpd after send some datapacket.  I'm sure the client didn't close the socket, but the httpd can't send response to client. 

The stack as following:

```
E/NanoHTTPD: Could not send response to the client
             java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                 at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:549)
                 at libcore.io.IoBridge.sendto(IoBridge.java:518)
                 at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
                 at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
                 at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
                 at org.nanohttpd.protocols.http.response.Response.sendBody(Response.java:333)
                 at org.nanohttpd.protocols.http.response.Response.sendBodyWithCorrectEncoding(Response.java:306)
                 at org.nanohttpd.protocols.http.response.Response.sendBodyWithCorrectTransferAndEncoding(Response.java:296)
                 at org.nanohttpd.protocols.http.response.Response.send(Response.java:263)
                 at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:455)
                 at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)
                 at java.lang.Thread.run(Thread.java:833)
              Caused by: android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
                 at libcore.io.Posix.sendtoBytes(Native Method)
                 at libcore.io.Posix.sendto(Posix.java:211)
                 at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
                 at libcore.io.IoBridge.sendto(IoBridge.java:516)
                 at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500) 
                 at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37) 
                 at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266) 
                 at org.nanohttpd.protocols.http.response.Response.sendBody(Response.java:333) 
                 at org.nanohttpd.protocols.http.response.Response.sendBodyWithCorrectEncoding(Response.java:306) 
                 at org.nanohttpd.protocols.http.response.Response.sendBodyWithCorrectTransferAndEncoding(Response.java:296) 
                 at org.nanohttpd.protocols.http.response.Response.send(Response.java:263) 
                 at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:455) 
                 at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75) 
                 at java.lang.Thread.run(Thread.java:833) 
I/System: core_booster, getBoosterConfig = false
I/System: core_booster, getBoosterConfig = false

```

**Comment by LordFokas** [comment]
This has probably been fixed, if it hasn't please reopen.

**Comment by Khoosham** [comment]
i have tried the fix it does not work
another error pops up

Could not send response to the client: java.io.IOException: read failed: EBADF (Bad file number)

**Comment by Khoosham** [comment]
i have read on stackoverflow that the error broken pipe occurs because of
the result of file limit on server side.

maybe the buffer size should be increased as it is only 16384 for now ??
