### ISSUE TITLE
Exceptions flood in ClientHandler.run() after SocketException: Broken pipe

### ISSUE THREAD

**Issue by sp20** [NanoHttpd/nanohttpd#397]
I have faced this situation when a client was connected through WebSocket and internet failed.
Here is the stack trace:

Thread: NanoHttpd Request Processor (#2468). ERROR fi.iki.elonen.NanoHTTPD - Could not send response to the client
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0]
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[na:1.8.0]
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153) ~[na:1.8.0]
	at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1622) ~[wheel.jar:na]
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1595) ~[wheel.jar:na]
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1585) ~[wheel.jar:na]
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1552) ~[wheel.jar:na]
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:939) [wheel.jar:na]
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:193) [wheel.jar:na]
	at java.lang.Thread.run(Thread.java:744) [na:1.8.0]

This exception was raising infinitely until the application was shut down.
I suppose the problem is that the socket was not closed on the exception which occurred in sendBodyWithCorrectTransferAndEncoding() (NanoHTTPD.java rel. 2.3.0, line 1552)

**Comment by LordFokas** [comment]
This has been fixed in dev, afaik.
Test with the latest code and tell me if you can reproduce it, please.

**Comment by sp20** [comment]
Ok, I'try.
But this problem occured under very specific conditions and I'm not sure that it can happen again very soon.

**Comment by LordFokas** [comment]
Oh it's a corner case? Bloody hell.

**Comment by LordFokas** [comment]
I'm going to close this, but if you can confirm this happens with the code currently in the master branch please reopen :)
