### ISSUE TITLE
Websocket: server read timed out

### ISSUE THREAD

**Issue by jebej** [NanoHttpd/nanohttpd#407]
Sorry if this is not the right place for this, I was trying to get the WebSocket example to run and it works, except that if a client does not continually send messages, the server will time out:

```
Server started, hit Enter to stop.

R WS[Text, fin, masked, [4b] test]
S WS[Text, fin, unmasked, [4b] test]
R WS[Text, fin, masked, [4b] test]
S WS[Text, fin, unmasked, [4b] test]
Dec 27, 2016 5:34:11 PM io.github.jebej.matlabwebsocket.DebugWebSocketServer$DebugWebSocket onException
SEVERE: exception occured
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at fi.iki.elonen.NanoWSD$WebSocketFrame.read(NanoWSD.java:435)
        at fi.iki.elonen.NanoWSD$WebSocket.readWebsocket(NanoWSD.java:248)
        at fi.iki.elonen.NanoWSD$WebSocket.access$200(NanoWSD.java:65)
        at fi.iki.elonen.NanoWSD$WebSocket$1.send(NanoWSD.java:88)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Unknown Source)
```

Is that normal?

**Comment by jebej** [comment]
Note that the same thing happens on master.

**Comment by LordFokas** [comment]
Yes, this is normal. You must ping/pong the socket to keep it alive.

**Comment by jebej** [comment]
Thanks for the reply. If you have the time, would you mind explaining what would be the best way to periodically/automatically ping the client?

I believe the library I was using before did it by default; it might be worthwhile to have that be the case here as well.

**Comment by LordFokas** [comment]
In my implementation I have a list of all the open websockets and a thread pings each of them in a loop then sleeps for 4 seconds. There might be better and more efficient ways, but this one works :)
