### ISSUE TITLE
compiling error (maven-jar-plugin)

### ISSUE THREAD

**Issue by Ygarr** [NanoHttpd/nanohttpd#428]
error while compile:

```
mvn exec:java -pl webserver -Dexec.mainClass="org.nanohttpd.SimpleWebServer"
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.nanohttpd:nanohttpd-websocket:jar:2.3.2-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ org.nanohttpd:nanohttpd-websocket:[unknown-version], ...nanohttpd/websocket/pom.xml, line 14, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.5.1/maven-release-plugin-2.5.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.5.1/maven-release-plugin-2.5.1.pom (11 KB at 4.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/release/maven-release/2.5.1/maven-release-2.5.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/release/maven-release/2.5.1/maven-release-2.5.1.pom (5 KB at 44.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.5.1/maven-release-plugin-2.5.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.5.1/maven-release-plugin-2.5.1.jar (50 KB at 248.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/tinyjee/dim/doxia-include-macro/1.1/doxia-include-macro-1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/tinyjee/dim/doxia-include-macro/1.1/doxia-include-macro-1.1.pom (15 KB at 66.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/tinyjee/dim/doxia-include-macro/1.1/doxia-include-macro-1.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/tinyjee/dim/doxia-include-macro/1.1/doxia-include-macro-1.1.jar (415 KB at 1107.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/2.15/maven-checkstyle-plugin-2.15.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/2.15/maven-checkstyle-plugin-2.15.pom (14 KB at 134.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/2.15/maven-checkstyle-plugin-2.15.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/2.15/maven-checkstyle-plugin-2.15.jar (109 KB at 708.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom (15 KB at 155.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom (0 B at 0.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar (204 KB at 1056.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.1/maven-release-plugin-2.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.1/maven-release-plugin-2.1.pom (9 KB at 79.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/release/maven-release/2.1/maven-release-2.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/release/maven-release/2.1/maven-release-2.1.pom (7 KB at 72.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.1/maven-release-plugin-2.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.1/maven-release-plugin-2.1.jar (40 KB at 359.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/maven-metadata.xml (741 B at 8.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.pom (13 KB at 124.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/40/mojo-parent-40.pom (33 KB at 312.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.6.0/exec-maven-plugin-1.6.0.jar (57 KB at 490.6 KB/sec)
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building NanoHttpd-Webserver 2.3.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/nanohttpd/nanohttpd/2.3.2-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/org/nanohttpd/nanohttpd/2.3.2-SNAPSHOT/maven-metadata.xml (990 B at 0.3 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/nanohttpd/nanohttpd/2.3.2-SNAPSHOT/nanohttpd-2.3.2-20170121.201122-17.pom
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/org/nanohttpd/nanohttpd/2.3.2-SNAPSHOT/nanohttpd-2.3.2-20170121.201122-17.pom (924 B at 2.8 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/nanohttpd/nanohttpd-project/2.3.2-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/org/nanohttpd/nanohttpd-project/2.3.2-SNAPSHOT/maven-metadata.xml (609 B at 1.8 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/nanohttpd/nanohttpd-project/2.3.2-SNAPSHOT/nanohttpd-project-2.3.2-20170121.201024-17.pom
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/org/nanohttpd/nanohttpd-project/2.3.2-SNAPSHOT/nanohttpd-project-2.3.2-20170121.201024-17.pom (14 KB at 29.2 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/nanohttpd/nanohttpd/2.3.2-SNAPSHOT/nanohttpd-2.3.2-20170121.201122-17.jar
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/org/nanohttpd/nanohttpd/2.3.2-SNAPSHOT/nanohttpd-2.3.2-20170121.201122-17.jar (53 KB at 85.1 KB/sec)
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ nanohttpd-webserver ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.pom (11 KB at 110.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar (54 KB at 470.3 KB/sec)
[WARNING] 
java.lang.ClassNotFoundException: org.nanohttpd.SimpleWebServer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:270)
	at java.lang.Thread.run(Thread.java:745)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.216 s
[INFO] Finished at: 2017-03-18T11:38:39+02:00
[INFO] Final Memory: 19M/162M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project nanohttpd-webserver: An exception occured while executing the Java class. org.nanohttpd.SimpleWebServer -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by LordFokas** [comment]
For versions <3.0 the package names are `fi.iki.elonen.*`, while for >=3.0 it has been refactored to `org.nanohttpd.*`
