### ISSUE TITLE
fi.iki.elonen.NanoHTTPD: Could not send response to the client,java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by MallikarjunaSH** [NanoHttpd/nanohttpd#444]
Hi, i am following the NanoHttpd sample code to srve videos for my android app and i am getting error like below:
fi.iki.elonen.NanoHTTPD: Could not send response to the client
                                                                                        java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
                                                                                            at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
                                                                                            at libcore.io.IoBridge.sendto(IoBridge.java:515)
                                                                                            at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
                                                                                            at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
                                                                                            at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
                                                                                            at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1369)
                                                                                            at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1620)
                                                                                            at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1593)
                                                                                            at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1580)
                                                                                            at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1550)
                                                                                            at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:937)
                                                                                            at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
                                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                                         Caused by: android.system.ErrnoException: sendto failed: ECONNRESET (Connection reset by peer)
                                                                                            at libcore.io.Posix.sendtoBytes(Native Method)
                                                                                            at libcore.io.Posix.sendto(Posix.java:206)
                                                                                            at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
                                                                                            at libcore.io.IoBridge.sendto(IoBridge.java:513)
                                                                                            at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504) 
                                                                                            at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37) 
                                                                                            at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266) 
                                                                                            at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1369) 
                                                                                            at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1620) 
                                                                                            at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1593) 
                                                                                            at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1580) 
                                                                                            at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1550) 
                                                                                            at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:937) 
                                                                                            at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192) 
                                                                                            at java.lang.Thread.run(Thread.java:818) 

Even i tried soo many things to overcome from this issue but couldnt comeup with any solutions so please help me in resolving this issue.
Thanks.

**Comment by Khoosham** [comment]
i think there is no way to solve that issue it was discussed before in other issues. just ignore it.
i have the same error but the video plays fine.

**Comment by faylite** [comment]
I'm having the same issue, except that I'm playing video in a Android WebView and the video crashes when this exception is thrown

**Comment by LordFokas** [comment]
We've been battling with this for **years**... honestly I wish someone would show up with a solution that would make that damned thing go away.

**Comment by cnlas** [comment]
the same problem,
After hours trying. I find a solution for Android VideoView。
first set the Android VideoView visibility to GONE when no video playing。
then set it visible after setVideoURI。
that means before setVideoURI，videoview is not visiable。
then，this damned exception disappear！
Maybe playing video in Webview is the same.
