### ISSUE TITLE
Second request of Two consecutive request fails

### ISSUE THREAD

**Issue by grragesh** [NanoHttpd/nanohttpd#466]
Dear Team,

Great project. Hats off! I have an issue.

I am hitting the same nano url from jMeter in a sequence. Every alternate hit passes. 

If I introduce a delay of 2 seconds, then every request passes.

The error is :  fi.iki.elonen.NanoHTTPD.execute - java.net.SocketException: NanoHttpd Shutdown
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:1044)
	at fi.iki.elonen.NanoHTTPD$2$1.run(NanoHTTPD.java:307)
	at java.lang.Thread.run(Thread.java:745)

This points to the below piece of code

 if (read == -1) {
                        // socket was been closed
                        safeClose(inputStream);
                        safeClose(outputStream);
                        throw new SocketException("NanoHttpd Shutdown");
                    }

**Comment by LordFokas** [comment]
Can you post example Request & Response HTTP packets for both the fail and the pass cases? Just so I can have a better look at it ;)

**Comment by grragesh** [comment]
Dear LordFokas,

Thank you for taking time to read my issue. Sorry I could not get the packet due to confidential reasons. But I will try to post masked one.  I have more info. The failure happens only when keep alive is true. To be more precise. The request after keep alive is failing. For example, if I have 5 requests in jmeter, and it is executed in sequence without gap, assume only the 3rd request has kerp-alive as true, then the 4tb request alone fails

**Comment by LordFokas** [comment]
Notice how I asked for example packets, it doesn't need to be production-grade stuff, packets on the foo-bar level are enough, as long as they are authentic. And that points really hard at the keep-alive system being faulty (which isn't new at all to me, it's worse than you can imagine)...

**Comment by LordFokas** [comment]
BTW v3 of NanoHTTPD fixes a lot of the "session" misbehavior, but I haven't managed to roll it out yet...

**Comment by grragesh** [comment]
Hi LordFokas,

Thank you. Yes keep alive system seems faulty. Sorry it was a client
environment so could not record. Will try to simulate the same and get the
packets. Thanks again for the support.


On 18-Nov-2017 10:32, "LordFokas" <notifications@github.com> wrote:

Notice how I asked for example packets, it doesn't need to be
production-grade stuff, packets on the foo-bar level are enough, as long as
they are authentic. And that points really hard at the keep-alive system
being faulty (which isn't new at all to me, it's worse than you can
imagine)...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NanoHttpd/nanohttpd/issues/466#issuecomment-345418799>,
or mute the thread

**Comment by grragesh** [comment]
Thanks @LordFokas,

Yes eagerly waiting for 3.x ;)


On 18-Nov-2017 10:33, "LordFokas" <notifications@github.com> wrote:

BTW v3 of NanoHTTPD fixes a lot of the "session" misbehavior, but I haven't
managed to roll it out yet...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NanoHttpd/nanohttpd/issues/466#issuecomment-345418842>,
or mute the thread

**Comment by fkoseoglu** [comment]
Hi @LordFokas, is there any progress on this issue? Also, any plans to roll out `3.0.0` anytime soon?

Thanks!

**Comment by LordFokas** [comment]
Not really. I don't think I can point at any single thing in that process and say *"oh look, that one thing isn't making my life hard on releasing 3.0"*

Most things are getting really complicated. When and if I have the time I might have to take a really radical approach to this...
