### ISSUE TITLE
Android --> java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by SteveKin3** [NanoHttpd/nanohttpd#477]
Error log:E/fi.iki.elonen.NanoHTTPD: Could not send response to the client

 java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)

Caused by: android.system.ErrnoException: sendto failed: ECONNRESET (Connection reset by peer)

in Android: jcifs->smb->http; is worked but show error. 

Play a Video, Every time you seek it, it make a error.

**Comment by denghewenai** [comment]
I had the same problem.

**Comment by JiannaiJ** [comment]
@denghewenai  Hi, were you able to solve this issue?

**Comment by denghewenai** [comment]
I'm still looking for reasons.

**Comment by pathikdevani** [comment]
@JiannaiJ are you using WebSocket?

**Comment by LordFokas** [comment]
@pathikdevani this is unrelated to websockets. This problem existed before websockets were even implemented. So far no one seems to really understand this.

**Comment by agosto-chrisdavis** [comment]
I'm seeing this error too and not just for video files.  By all accounts everything seems to be working, so not sure what is generating the error, but I see it a lot.   Same setup. Android/webview. 

`E/fi.iki.elonen.NanoHTTPD: Could not send response to the client
java.net.SocketException: sendto failed: ECONNRESET (Connection reset by peer)
at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:499)
at libcore.io.IoBridge.sendto(IoBridge.java:468)
at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507)
at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269)
at java.io.OutputStream.write(OutputStream.java:82)
at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1442)
at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1430)
at java.util.zip.GZIPOutputStream.writeShort(GZIPOutputStream.java:127)
at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:83)
at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:54)
at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1663)
at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1654)
at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
at java.lang.Thread.run(Thread.java:841)
Caused by: libcore.io.ErrnoException: sendto failed: ECONNRESET (Connection reset by peer)
at libcore.io.Posix.sendtoBytes(Native Method)
at libcore.io.Posix.sendto(Posix.java:156)
at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
at libcore.io.IoBridge.sendto(IoBridge.java:466)
at java.net.PlainSocketImpl.write(PlainSocketImpl.java:507) 
at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46) 
at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:269) 
at java.io.OutputStream.write(OutputStream.java:82) 
at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1442) 
at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1430) 
at java.util.zip.GZIPOutputStream.writeShort(GZIPOutputStream.java:127) 
at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:83) 
at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:54) 
at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1663) 
at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1654) 
at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624) 
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957) 
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192) 
at java.lang.Thread.run(Thread.java:841) `

**Comment by fit-aditya** [comment]
Any solution to this?

**Comment by LordFokas** [comment]
Not that we know of.

**Comment by adityagoel19** [comment]
Okay, any alternatives to NanoHttpd that do not have this? This issue is sort of a deal breaker.

**Comment by LordFokas** [comment]
Not that I know of. I might end up rewriting the whole thing with a much better architecture but it will probably take me a good while.

**Comment by NoahAndrews** [comment]
What triggers the issue?
