### ISSUE TITLE
InputStream has been making a mistake when dragging the video

### ISSUE THREAD

**Issue by wu19910708** [NanoHttpd/nanohttpd#483]
java.io.IOException: read failed: EBADF (Bad file number)
                                                                                           at libcore.io.IoBridge.read(IoBridge.java:522)
                                                                                           at java.io.FileInputStream.read(FileInputStream.java:177)
                                                                                           at httpd.protocols.http.response.Response.sendBody(Response.java:350)
                                                                                           at httpd.protocols.http.response.Response.sendBodyWithCorrectEncoding(Response.java:327)
                                                                                           at httpd.protocols.http.response.Response.sendBodyWithCorrectTransferAndEncoding(Response.java:314)
                                                                                           at httpd.protocols.http.response.Response.send(Response.java:277)
                                                                                           at httpd.protocols.http.HTTPSession.execute(HTTPSession.java:434)
                                                                                           at httpd.protocols.http.ClientHandler.run(ClientHandler.java:76)
                                                                                           at java.lang.Thread.run(Thread.java:818)

**Comment by dreamsdeng110** [comment]
I've met it, too

07-28 10:19:01.200 20902-21280/com.hujiang.nano E/fi.iki.elonen.NanoHTTPD: Could not send response to the client
    java.net.SocketException: sendto failed: EBADF (Bad file number)
        at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
        at libcore.io.IoBridge.sendto(IoBridge.java:515)
        at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504)
        at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37)
        at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
        at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1694)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1667)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1657)
        at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:980)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: sendto failed: EBADF (Bad file number)
        at libcore.io.Posix.sendtoBytes(Native Method)
        at libcore.io.Posix.sendto(Posix.java:206)
        at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
        at libcore.io.IoBridge.sendto(IoBridge.java:513)
        at java.net.PlainSocketImpl.write(PlainSocketImpl.java:504) 
        at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:37) 
        at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266) 
        at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1694) 
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1667) 
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1657) 
        at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624) 
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:980) 
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192) 
        at java.lang.Thread.run(Thread.java:818)
