### ISSUE TITLE
Error for POST response Could not send response to the client java.net.SocketException: Socket closed

### ISSUE THREAD

**Issue by felislynx-silae** [NanoHttpd/nanohttpd#486]
I'm sending simple response for POST request 
`newFixedLengthResponse(
                            NanoHTTPD.Response.Status.OK,
                            MIME_PLAINTEXT, "OK"
                        )`
And i've got this error:
`E/fi.iki.elonen.NanoHTTPD: Could not send response to the client
    java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
        at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1442)
        at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1435)
        at java.util.zip.GZIPOutputStream.writeHeader(GZIPOutputStream.java:182)
        at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:94)
        at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:109)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1663)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1654)
        at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
        at java.lang.Thread.run(Thread.java:764)`
For GET request i can send response and nothing like this happens

**Comment by HussainYousuf** [comment]
Are you pinging?

**Comment by felislynx-silae** [comment]
Nope.
Scenario:
- Server is working
- i send rest GET request server is responding with OK
- i send POST request server throws an error
- i send GET request server is responding with OK
every time post request is send, server cannot respond because of this error, but for get it works every time

**Comment by HussainYousuf** [comment]
Will you will have to ping, send ping to client from the server the client will automatically pong

**Comment by HussainYousuf** [comment]
nanohttpd  has socket timeout to 5 seconds i think after which it closes the socket so you will have to periodically poll to keep the connection active

**Comment by felislynx-silae** [comment]
I've set different times and also i've tried negative value to set to never timeout.

**Comment by felislynx-silae** [comment]
Also, situation on typical REST communication where i should ping server is abnormal

**Comment by stsatlantis** [comment]
@felislynx-silae have you managed to workaround this problem?

**Comment by felislynx-silae** [comment]
@stsatlantis nope, i've changed server. i didn't have time to wait for fix

**Comment by xotonic** [comment]
I've got this error too with a handling POST request on 2.3.1

```
$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

**Comment by davidgiga1993** [comment]
~~Me too, JDK 14~~
The issue is occurs as soon as you close the input stream (e.g. when parsing the POST payload). If you keep the input stream still open it works.
