### ISSUE TITLE
Could not send response to the client

### ISSUE THREAD

**Issue by rasoulinejad** [NanoHttpd/nanohttpd#508]
android device : moto c ,android 7.0
nanohttpd-webserver:2.2.0
this error occur 4-5 minute after screen off 

Could not send response to the client
    java.net.SocketException: Software caused connection abort
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:112)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
        at fi.iki.elonen.NanoHTTPD$Response.sendBody(NanoHTTPD.java:1480)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1453)
        at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1443)
        at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1429)
        at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:852)
        at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
        at java.lang.Thread.run(Thread.java:761)

**Comment by timehaswings** [comment]
I have encountered the same problem. How to solve it?

**Comment by Sailiy** [comment]
我是用websocket，也遇到了同样的问题
