### ISSUE TITLE
SSL_ERROR_NO_CYPHER_OVERLAP

### ISSUE THREAD

**Issue by iillyyaa2033** [NanoHttpd/nanohttpd#514]
Https stopped working properly after letsencrypt's certificate renewal. Previous 30 day all have been working fine.

This is screenshot from Firefox:
![image](https://user-images.githubusercontent.com/17745136/46913835-81d78380-cf9d-11e8-83b9-a45166ab9dea.png)

And this is server's log lines about this event:
```
javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: no cipher suites in common
	at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1551)
	at sun.security.ssl.SSLSocketImpl.checkWrite(SSLSocketImpl.java:1563)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:71)
	at java.io.OutputStream.write(OutputStream.java:75)
	at org.nanohttpd.protocols.http.response.ChunkedOutputStream.write(ChunkedOutputStream.java:68)
	at org.nanohttpd.protocols.http.response.ChunkedOutputStream.write(ChunkedOutputStream.java:61)
	at java.util.zip.GZIPOutputStream.writeHeader(GZIPOutputStream.java:182)
	at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:94)
	at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:109)
	at org.nanohttpd.protocols.http.response.Response.sendBodyWithCorrectEncoding(Response.java:308)
	at org.nanohttpd.protocols.http.response.Response.sendBodyWithCorrectTransferAndEncoding(Response.java:299)
	at org.nanohttpd.protocols.http.response.Response.send(Response.java:268)
	at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:450)
	at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: no cipher suites in common
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
	at sun.security.ssl.ServerHandshaker.chooseCipherSuite(ServerHandshaker.java:1115)
	at sun.security.ssl.ServerHandshaker.clientHello(ServerHandshaker.java:807)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:228)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:938)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:357)
	... 2 more
```

How I'm making connection secure at server startup:
![image](https://user-images.githubusercontent.com/17745136/46913902-c879ad80-cf9e-11e8-8aa5-9c6c65d55e89.png)

Can you help me solve this problem?

**Comment by iillyyaa2033** [comment]
My fault. Closing issue.
