### ISSUE TITLE
Issue #392 wasn't properly fixed

### ISSUE THREAD

**Issue by evgk** [NanoHttpd/nanohttpd#524]
Here is the stack trace:

    javax.net.ssl.SSLException: Write error: ssl=0xec6d3908: I/O error during system call, Broken pipe
        at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
        at com.android.org.conscrypt.NativeSsl.write(NativeSsl.java:414)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:623)
        at java.io.OutputStream.write(OutputStream.java:75)
        at org.nanohttpd.protocols.http.response.ChunkedOutputStream.write(ChunkedOutputStream.java:68)
        at org.nanohttpd.protocols.http.response.ChunkedOutputStream.write(ChunkedOutputStream.java:61)
        at java.util.zip.GZIPOutputStream.writeHeader(GZIPOutputStream.java:182)
        at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:94)
        at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:109)
        at org.nanohttpd.protocols.http.response.Response.sendBodyWithCorrectEncoding(Response.java:308)
        at org.nanohttpd.protocols.http.response.Response.sendBodyWithCorrectTransferAndEncoding(Response.java:299)
        at org.nanohttpd.protocols.http.response.Response.send(Response.java:268)
        at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:458)
        at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)

So GZIPOutputStream calls WriteHeader in it's constructor which writes to ChunkedOutputStream. If the client abruptly closes the connection, then the same exception as in #392 is raised.

**Comment by LordFokas** [comment]
@evgk can I close this now?

**Comment by LordFokas** [comment]
@evgk run your tests again in the master branch, if it has been properly fixed please close this, otherwise commit a better fix ;)

**Comment by evgk** [comment]
Hi,
  Yes, seems to be solved now. Thanks.
