### ISSUE TITLE
If site could not be found,the tempfile will not be deleted,how to resolve this problem?

### ISSUE THREAD

**Issue by superbigdog** [NanoHttpd/nanohttpd#581]
`五月 13, 2020 2:56:46 下午 fi.iki.elonen.NanoHTTPD$DefaultTempFileManager clear

警告: could not delete file 
java.lang.Exception: could not delete temporary file: *********\Temp\NanoHTTPD-4713709955631918165
	at fi.iki.elonen.NanoHTTPD$DefaultTempFile.delete(NanoHTTPD.java:403)
	at fi.iki.elonen.NanoHTTPD$DefaultTempFileManager.clear(NanoHTTPD.java:446)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:984)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:745)`

and also this tempfile does not release by JVM.

**Comment by superbigdog** [comment]
add an error website to finish the  request.
